#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Apr 15, 2018 06:16:17 PM
# Author : Sagar Raghupathi



import sys
import os

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global Se
    Se = StringVar()

def close():
    print('*************Thank-You*************')
    sys.exit()
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def get_file_list():
    return [name for name in os.listdir(r'C:\Users\GOOGLE 100\Desktop\attachments\Look Based Media Player\Video_Source') if name.endswith(".mp4")]

if __name__ == '__main__':
    import Gui
    Gui.vp_start_gui()


